### ISSUE TITLE
Suggestion: Change title color

### ISSUE THREAD

**Issue by mike-loux-planview** [BaconTentacles/github-crash-course#1]
Hey, personal Mike, it's work Mike.  
Doing this issue as a means of experimenting with contributors and whatnot
I think it looks better if the main title is a bit more orange.
The styling rule could be changed like this:

```css
h1 {
  color: #efa82e;
}
```

**Comment by BaconTentacles** [comment]
Cool.  Go for it.  
Love and kisses, personal Mike.
